### ISSUE TITLE
Readme - What does " Change CMakeFile, path of the DSO Library.`" mean?

### ISSUE THREAD

**Issue by brgrp** [goktug97/dso_ros2#1]
Hi, I am currently trying to run your wrapper.
Could you please specify what you mean by:_

`[DSO SLAM library](https://github.com/JakobEngel/dso) Change CMakeFile, path of the DSO Library.`

Big thanks

**Comment by goktug97** [comment]
Hi, you need to change line 37 in dso/CMakeLists.txt (this repo) to cloned path of dso (https://github.com/JakobEngel/dso)
Also you need to compile the dso.
